[project]
name = "new-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.26.0",
    "langchain>=0.3.24",
    "langchain-openai>=0.3.14",
    "openai>=1.76.0",
]
